name: Upload assets to R2

on:
  push:
    branches:
      - main
    paths:
      - assets/**
      - .github/workflows/r2_upload.yml

jobs:

  r2_upload_original:
    name: R2 Upload Full Res Original
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: assets/original
        
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [r2]
            type = s3
            provider = Cloudflare
            region = auto
            env_auth = true
          disable_base64: true

      - run: rclone sync --verbose --no-update-modtime assets/original/ r2:gran-assets/original/
        env:
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/


  r2_upload_enhanced:
    name: R2 Upload Full Res Enhanced
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: assets/enhanced
        
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [r2]
            type = s3
            provider = Cloudflare
            region = auto
            env_auth = true
          disable_base64: true

      - run: rclone sync --verbose --no-update-modtime assets/enhanced/ r2:gran-assets/enhanced/
        env:
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/

  r2_upload_recipe_crops:
    name: R2 Upload Full Res Recipe Crops
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: assets/recipe_crops

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [r2]
            type = s3
            provider = Cloudflare
            region = auto
            env_auth = true
          disable_base64: true

      - run: rclone sync --verbose --no-update-modtime assets/recipe_crops/ r2:gran-assets/recipe_crops/
        env:
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/

  r2_upload_recipe_photos:
    name: R2 Upload Full Res Recipe Photos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: assets/recipe_photos

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [r2]
            type = s3
            provider = Cloudflare
            region = auto
            env_auth = true
          disable_base64: true

      - run: rclone sync --verbose --no-update-modtime assets/recipe_photos/ r2:gran-assets/recipe_photos/
        env:
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/

  r2_upload_homepage:
    name: R2 Upload Full Homepage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: assets/homepage

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: |
            [r2]
            type = s3
            provider = Cloudflare
            region = auto
            env_auth = true
          disable_base64: true

      - run: rclone sync --verbose --no-update-modtime assets/homepage/ r2:gran-assets/homepage/
        env:
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/
